export const scheduleData = [
  {
    id: "101",
    day: "SELASA",
    time: "15.00-17.30",
    code: "FIK61545",
    subject: "METODOLOGI PENELITIAN",
    credits: 3,
    lecturer: "Didi Juardi, S.T., M.Kom.",
    group: "KELAS WAJIB",
    room: "Kelas 4.76 - 2",
    department: "IF",
  },
  {
    id: "102",
    day: "KAMIS",
    time: "12.30-15.00",
    code: "FIK61548",
    subject: "SOFTWARE DESIGN PATTERN",
    credits: 3,
    lecturer: "Carudin, M.Kom.",
    group: "KELAS WAJIB",
    room: "Kelas 4.75 - 1",
    department: "IF",
  },
  {
    id: "103",
    day: "RABU",
    time: "12.30-15.00",
    code: "FIK61547",
    subject: "PENGOLAHAN CITRA DIGITAL",
    credits: 3,
    lecturer: "Aries Suharso, S.Si., M.Kom.",
    group: "KELAS WAJIB",
    room: "LAB DASAR 1",
    department: "IF",
  },
  {
    id: "104",
    day: "KAMIS",
    time: "10.00-12.30",
    code: "FIK61546",
    subject: "MACHINE LEARNING",
    credits: 3,
    lecturer: "Budi Arif Dermawan, M.Kom.",
    group: "KELAS WAJIB",
    room: "LAB DASAR 1",
    department: "IF",
  },
  {
    id: "105",
    day: "JUM'AT",
    time: "15.30-18.00",
    code: "FIK61543",
    subject: "MANAJEMEN PROYEK PERANGKAT LUNAK",
    credits: 3,
    lecturer: "Rini Mayasari, M.Kom.",
    group: "KELAS WAJIB",
    room: "LAB LANJUT 1",
    department: "IF",
  },
  {
    id: "121",
    day: "RABU",
    time: "07.30-10.00",
    code: "FIK61557",
    subject: "WIRELESS SENSOR NETWORK",
    credits: 3,
    lecturer: "E. Haodudin Nurkifli, S.T., M.Cs., Ph.D.",
    group: "KELAS PILIHAN",
    room: "Kelas 4.76 - 2",
    department: "IF",
    session: "SESI 1"
  },
  {
    id: "121B",
    day: "SABTU",
    time: "10.00-12.30",
    code: "FIK61557",
    subject: "WIRELESS SENSOR NETWORK",
    credits: 3,
    lecturer: "E. Haodudin Nurkifli, S.T., M.Cs., Ph.D.",
    group: "KELAS PILIHAN",
    room: "Kelas 4.76 - 2",
    department: "IF",
    session: "SESI 2"
  },
  {
    id: "122",
    day: "KAMIS",
    time: "10.00-12.30",
    code: "FIK61544",
    subject: "SISTEM PENDUKUNG KEPUTUSAN",
    credits: 3,
    lecturer: "Dr. Jajam Haerul Jaman, S.E., M.Kom.",
    group: "KELAS PILIHAN",
    room: "Kelas 4.78 - 4",
    department: "IF",
  },
  {
    id: "123",
    day: "JUM'AT",
    time: "10.00-12.30",
    code: "FIK61563",
    subject: "PERANCANGAN USER EXPERIENCE",
    credits: 3,
    lecturer: "Siska, M.kom.",
    group: "KELAS PILIHAN",
    room: "Kelas 4.76 - 2",
    department: "IF",
  },
  {
    id: "124",
    day: "RABU",
    time: "10.00-12.30",
    code: "FIK61554",
    subject: "BUSINESS INTELIGENCE",
    credits: 3,
    lecturer: "Aji Primajaya, S.Si., M.Kom.",
    group: "KELAS PILIHAN",
    room: "LAB DASAR 2",
    department: "IF",
  },
  {
    id: "125",
    day: "SABTU",
    time: "07.30-10.00",
    code: "FIK61550",
    subject: "ANALISIS BIG DATA",
    credits: 3,
    lecturer: "Ratna Mufidah, M.Kom.",
    group: "KELAS PILIHAN",
    room: "Kelas 4.77 - 5",
    department: "IF",
  },
  {
    id: "126",
    day: "JUM'AT",
    time: "13.00-15.30",
    code: "FIK61559",
    subject: "NETWORK MANAGEMENT",
    credits: 3,
    lecturer: "Purwantoro, M.Kom.",
    group: "KELAS PILIHAN",
    room: "LAB LANJUT 2",
    department: "IF",
  },
];

export const dayColors = {
  SENIN: "bg-blue-100 border-l-4 border-blue-500",
  SELASA: "bg-green-100 border-l-4 border-green-500",
  RABU: "bg-yellow-100 border-l-4 border-yellow-500",
  KAMIS: "bg-purple-100 border-l-4 border-purple-500",
  "JUM'AT": "bg-pink-100 border-l-4 border-pink-500",
  SABTU: "bg-orange-100 border-l-4 border-orange-500",
};

export const dayOrder = {
  SENIN: 1,
  SELASA: 2,
  RABU: 3,
  KAMIS: 4,
  "JUM'AT": 5,
  SABTU: 6,
  MINGGU: 7
};
